// SecretRoom admin phase two: case assignments, selections and My Tasks.
(() => {
  if(window.__SR_ADMIN_PHASE2_CASE_LIST__)return;
  window.__SR_ADMIN_PHASE2_CASE_LIST__=true;
  const APP_ID='secretg-production-node-tw',VERSION='20260711-admin-phase2-case-list-v1',SESSION='sr_admin_session_id_v2';
  const assignments=new Map(),selected=new Map();
  let unsub=null,queued=false,myOnly=false;
  const qs=id=>document.getElementById(id),tx=v=>String(v||'').replace(/\s+/g,' ').trim(),toast=(m,t='info')=>window.showToast?.(m,t);
  async function tools(){const a=await import('https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js'),fs=await import('https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js'),app=a.getApps()[0];if(!app)throw Error('Firebase 尚未初始化');return{db:fs.getFirestore(app),fs};}
  const adminId=()=>window.SRAdminPhase2?.adminId||sessionStorage.getItem(SESSION)||qs('admin-login-id')?.value.trim()||'';
  const can=a=>window.SRAdminPhase2?.can?window.SRAdminPhase2.can(a):true;
  function caseId(card){const attrs=[...card.querySelectorAll('[onclick]')].map(n=>n.getAttribute('onclick')||'').join(' '),quoted=attrs.match(/\(['"]([^'"]+)['"]/),account=tx(card).match(/@([A-Za-z0-9_.-]+)/)?.[1],post=tx(card).match(/貼文 ID[:：]\s*([^\s·]+)/)?.[1];return quoted?.[1]||post||account||tx(card).slice(0,80);}
  function caseKey(card){return`${qs('filter-status')?.value||'all'}:${caseId(card)}`;}
  function hash(v){let h=5381;for(let i=0;i<v.length;i++)h=((h<<5)+h)^v.charCodeAt(i);return`case_${(h>>>0).toString(36)}`;}
  async function assign(key,to){if(!can('assign_self'))throw Error('你的角色不能指派案件。');const{db,fs}=await tools();await fs.setDoc(fs.doc(db,'secretg_apps',APP_ID,'admin_case_assignments',hash(key)),{caseKey:key,assignedTo:to,assignedBy:adminId(),status:to?'assigned':'unassigned',updatedAt:fs.serverTimestamp(),updatedAtMs:Date.now()},{merge:true});}
  async function sync(){if(unsub)return;try{const{db,fs}=await tools();unsub=fs.onSnapshot(fs.collection(db,'secretg_apps',APP_ID,'admin_case_assignments'),s=>{assignments.clear();s.forEach(d=>{const x=d.data()||{};if(x.caseKey)assignments.set(x.caseKey,{id:d.id,...x});});schedule();},e=>console.warn('案件指派同步失敗',e));}catch(e){console.warn(e);}}
  function decorate(card){if(card.dataset.srPhase2Selectable==='1'||/目前沒有|正在讀取|正在檢索/.test(tx(card)))return;card.dataset.srPhase2Selectable='1';const key=caseKey(card);card.dataset.srCaseKey=key;card.style.position='relative';card.style.paddingLeft='3.2rem';const label=document.createElement('label');label.className='sr-case-checkbox absolute top-3 left-3 w-8 h-8 rounded-lg border border-slate-700 bg-slate-950/90 flex items-center justify-center z-10';label.innerHTML='<input type="checkbox" class="accent-amber-500">';card.appendChild(label);const input=label.querySelector('input');input.checked=selected.has(key);input.onchange=()=>{input.checked?selected.set(key,card):selected.delete(key);update();};const a=assignments.get(key);if(a?.assignedTo&&!card.querySelector('.sr-case-assignee')){const tag=document.createElement('div');tag.className='sr-case-assignee absolute top-3 right-3 text-[11px] px-2 py-1 rounded-full border border-cyan-500/20 bg-cyan-500/5 text-cyan-300 font-black';tag.textContent=a.assignedTo===adminId()?'我的案件':`負責：${a.assignedTo}`;card.appendChild(tag);}}
  function toolbar(){const list=qs('admin-list');if(!list||qs('sr-admin-batch-v2'))return;const bar=document.createElement('div');bar.id='sr-admin-batch-v2';bar.className='mb-3 rounded-2xl border border-violet-500/15 bg-violet-500/5 p-3 flex flex-col md:flex-row md:items-center md:justify-between gap-3';bar.innerHTML='<div><strong id="sr-batch-count" class="text-sm text-slate-200">已選 0 筆</strong><div class="text-xs text-slate-500 mt-1">批次操作只提供指派與匯出，不直接批次刪除或核准。</div></div><div class="flex flex-wrap gap-2"><button id="sr-batch-myself" class="min-h-[44px] px-4 rounded-xl bg-violet-600 text-white text-xs font-black">指派給我</button><button id="sr-batch-export" class="min-h-[44px] px-4 rounded-xl border border-slate-700 text-slate-300 text-xs font-black">匯出選取內容</button><button id="sr-my-tasks-toggle" class="min-h-[44px] px-4 rounded-xl border border-cyan-500/20 text-cyan-300 text-xs font-black">只看我的待辦</button></div>';list.parentElement.insertBefore(bar,list);qs('sr-batch-myself').onclick=async()=>{if(!selected.size)return toast('請先選取案件。','info');try{for(const key of selected.keys())await assign(key,adminId());selected.clear();document.querySelectorAll('.sr-case-checkbox input').forEach(i=>i.checked=false);update();toast('已把選取案件指派給你。','success');}catch(e){toast(e.message,'error');}};qs('sr-batch-export').onclick=()=>{if(!selected.size)return toast('請先選取案件。','info');const data=[...selected].map(([key,card])=>({caseKey:key,text:tx(card)})),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`secretroom_admin_cases_${Date.now()}.json`;a.click();URL.revokeObjectURL(url);};qs('sr-my-tasks-toggle').onclick=()=>{myOnly=!myOnly;schedule();};}
  function update(){if(qs('sr-batch-count'))qs('sr-batch-count').textContent=`已選 ${selected.size} 筆`;if(qs('sr-my-tasks-toggle'))qs('sr-my-tasks-toggle').textContent=myOnly?'顯示全部案件':'只看我的待辦';document.querySelectorAll('#admin-list>[data-sr-case-key]').forEach(card=>{const to=assignments.get(card.dataset.srCaseKey)?.assignedTo||'';card.classList.toggle('hidden',myOnly&&to!==adminId());});}
  function style(){if(qs('sr-admin-phase2-case-list-style'))return;const s=document.createElement('style');s.id='sr-admin-phase2-case-list-style';s.textContent='.sr-case-checkbox{opacity:.72}.sr-case-checkbox:hover{opacity:1}@media(max-width:640px){.sr-case-assignee{position:static!important;display:inline-flex;margin-bottom:.5rem}}';document.head.appendChild(s);}
  function apply(){queued=false;style();sync();toolbar();document.querySelectorAll('#admin-list>div').forEach(decorate);update();window.SRAdminCaseWorkspace={...(window.SRAdminCaseWorkspace||{}),assignments,selected,caseId,caseKey,assign,hash,tools};document.documentElement.dataset.srAdminPhase2CaseList=VERSION;}
  function schedule(){if(queued)return;queued=true;requestAnimationFrame(apply);}
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});apply();
})();
