// SecretRoom admin phase two: role-aware controls and role management.
(() => {
  if(window.__SR_ADMIN_PHASE2_ROLES__)return;
  window.__SR_ADMIN_PHASE2_ROLES__=true;
  const APP_ID='secretg-production-node-tw',VERSION='20260711-admin-phase2-roles-v1',SESSION='sr_admin_session_id_v2';
  let adminId='',adminData=null,queued=false;
  const qs=id=>document.getElementById(id),toast=(m,t='info')=>window.showToast?.(m,t),tx=v=>String(v||'').replace(/\s+/g,' ').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function tools(){const a=await import('https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js'),fs=await import('https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js'),app=a.getApps()[0];if(!app)throw Error('Firebase 尚未初始化');return{db:fs.getFirestore(app),fs};}
  function capture(){const v=qs('admin-login-id')?.value.trim();if(v)sessionStorage.setItem(SESSION,v);adminId=sessionStorage.getItem(SESSION)||v||'';window.SRAdminPhase2=window.SRAdminPhase2||{};window.SRAdminPhase2.adminId=adminId;}
  function role(){const v=String(adminData?.adminRole||adminData?.role||'').toLowerCase();if(['owner','manager','reviewer','viewer'].includes(v))return v;return adminData?.role==='admin'||adminData?.isAdmin?'owner':'viewer';}
  function label(v=role()){return({owner:'Owner',manager:'Manager',reviewer:'Reviewer',viewer:'Viewer'})[v]||'Viewer';}
  function can(action){const r=role();if(r==='owner')return true;if(r==='manager')return action!=='manage_roles';if(r==='reviewer')return['view','review','assign_self','note','image_review'].includes(action);return action==='view';}
  function action(button){const s=tx(button);if(/永久刪除|核准並刪除|刪除帳號/.test(s))return'delete_account';if(/刪除貼文|刪除留言|下架/.test(s))return'delete_content';if(/發送平台通知|重新寄送|寄出 10 分鐘臨時密碼/.test(s))return'send';if(/通過|核准|拒絕|駁回|設定新密碼|標記已處理/.test(s))return'review';return'view';}
  async function load(){capture();if(!adminId||adminData)return;try{const{db,fs}=await tools(),s=await fs.getDoc(fs.doc(db,'secretg_apps',APP_ID,'admins',adminId));adminData=s.exists()?{id:s.id,...s.data()}:{id:adminId,adminRole:'viewer'};window.SRAdminPhase2={...(window.SRAdminPhase2||{}),adminId,adminData,role:role(),can};renderBadge();renderManager();schedule();}catch(e){console.warn('管理員角色讀取失敗',e);}}
  function renderBadge(){const h=document.querySelector('#admin-main header');if(!h||!adminData)return;let b=qs('sr-admin-role-badge-v2');if(!b){b=document.createElement('div');b.id='sr-admin-role-badge-v2';b.className='self-start px-3 py-2 rounded-full border border-violet-500/20 bg-violet-500/10 text-violet-200 text-xs font-black';h.appendChild(b);}b.textContent=`${adminId} · ${label()}`;b.title='介面角色限制需搭配 Firestore Security Rules 才是完整安全控制。';}
  async function renderManager(){const main=qs('admin-main');if(!main||!adminData||qs('sr-role-manager-v2'))return;const p=document.createElement('section');p.id='sr-role-manager-v2';p.className='mb-8 rounded-3xl border border-violet-500/15 bg-violet-500/5 p-5';p.innerHTML=`<div class="flex items-center justify-between gap-3"><div><div class="text-xs text-violet-300 font-black">後台角色</div><h2 class="text-lg text-white font-black mt-1">權限與分工</h2><p class="text-xs text-slate-500 mt-1">Owner 可調整角色；Manager 管理案件；Reviewer 審核內容；Viewer 僅檢視。</p></div><button id="sr-role-toggle" class="min-h-[44px] px-4 rounded-xl border border-violet-500/20 text-violet-300 text-xs font-black">${can('manage_roles')?'管理角色':label()}</button></div><div id="sr-role-list" class="hidden grid grid-cols-1 md:grid-cols-2 gap-3 mt-4"></div>`;main.querySelector('header')?.insertAdjacentElement('afterend',p);qs('sr-role-toggle').onclick=async()=>{if(!can('manage_roles'))return toast('只有 Owner 可以調整後台角色。','info');const list=qs('sr-role-list');list.classList.toggle('hidden');if(list.dataset.loaded==='1')return;try{const{db,fs}=await tools(),snap=await fs.getDocs(fs.collection(db,'secretg_apps',APP_ID,'admins')),rows=[];snap.forEach(d=>rows.push({id:d.id,...d.data()}));list.innerHTML=rows.map(x=>`<div class="rounded-2xl border border-slate-800 bg-slate-950/55 p-4"><div class="text-sm text-slate-200 font-black">${esc(x.id)}</div><select data-admin-role="${esc(x.id)}" class="w-full min-h-[44px] mt-3 rounded-xl bg-slate-900 border border-slate-700 px-3 text-xs text-slate-200"><option value="owner">Owner</option><option value="manager">Manager</option><option value="reviewer">Reviewer</option><option value="viewer">Viewer</option></select></div>`).join('');rows.forEach(x=>{const s=list.querySelector(`[data-admin-role="${CSS.escape(x.id)}"]`);s.value=x.adminRole||(x.role==='admin'?'owner':'viewer');s.onchange=async()=>{try{await fs.updateDoc(fs.doc(db,'secretg_apps',APP_ID,'admins',x.id),{adminRole:s.value,roleUpdatedBy:adminId,roleUpdatedAt:fs.serverTimestamp(),roleUpdatedAtMs:Date.now()});toast(`${x.id} 已改為 ${label(s.value)}。`,'success');}catch(e){toast('角色更新失敗：'+e.message,'error');}};});list.dataset.loaded='1';}catch(e){toast('角色清單讀取失敗：'+e.message,'error');}};}
  function guard(){document.querySelectorAll('#admin-list button,#sr-notification-scheduler-v2 button').forEach(b=>{const ok=can(action(b));b.classList.toggle('sr-role-disabled',!ok);b.setAttribute('aria-disabled',ok?'false':'true');if(!ok)b.title=`${label()} 無法執行這個操作`;});}
  function style(){if(qs('sr-admin-phase2-roles-style'))return;const s=document.createElement('style');s.id='sr-admin-phase2-roles-style';s.textContent='.sr-role-disabled{opacity:.42!important;filter:grayscale(.35);cursor:not-allowed!important}';document.head.appendChild(s);}
  function apply(){queued=false;style();capture();load();renderBadge();renderManager();guard();document.documentElement.dataset.srAdminPhase2Roles=VERSION;}
  function schedule(){if(queued)return;queued=true;requestAnimationFrame(apply);}
  document.addEventListener('click',e=>{if(e.target?.closest?.('#admin-login-submit'))capture();const b=e.target?.closest?.('.sr-role-disabled');if(b){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();toast(`${label()} 無法執行這個操作。`,'error');}},true);
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});apply();
})();
