(()=>{
  if(window.__SR_DAILY_VERIFICATION_V1__)return;
  window.__SR_DAILY_VERIFICATION_V1__=true;
  const DAY=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Taipei"});
  const KEY='sr_daily_verification_v1';
  const TASKS=[
    {q:'情境：對方說「黃燈」。你第一個動作應該是？',a:['立即停止並確認狀況','繼續但降低速度','先完成目前動作再詢問'],c:0,n:'黃燈代表需要立即放慢、調整或確認，不應自行解讀成繼續。'},
    {q:'在開始新的 BDSM 情境前，最重要的是先確認什麼？',a:['彼此同意、界線與停止方式','誰的社群人氣比較高','是否已經有人按讚'],c:0,n:'先談共識、界線與安全訊號，才能讓雙方知道何時停止或調整。'},
    {q:'「紅燈」在常見安全詞系統中代表什麼？',a:['立即停止','降低強度','可以繼續'],c:0,n:'紅燈是明確的停止訊號；收到後應立即停止並確認對方狀況。'},
    {q:'活動結束後，哪一項最符合 aftercare 的概念？',a:['確認彼此身心狀況並照顧後續感受','立刻離開、不再聯絡','只記錄誰的評分比較高'],c:0,n:'Aftercare 重點是確認身心狀態、提供需要的照顧並尊重彼此後續感受。'},
    {q:'在會員內容中分享他人資訊前，最安全的做法是？',a:['先取得對方明確同意，並避免可識別資訊','只要自己覺得沒問題就可以','先公開再詢問'],c:0,n:'同意與隱私優先；未經同意不要公開可識別的個人資訊。'},
    {q:'對方沒有明確表示同意新的活動或界線變更時，應該怎麼做？',a:['先停下來確認','自行判斷對方應該可以','交給旁觀者決定'],c:0,n:'沒有明確同意時不要自行推定；先確認，再決定是否繼續。'}
  ];
  const css=`#sr-daily-verification{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:16px;background:rgba(3,5,8,.96);backdrop-filter:blur(18px)}#sr-daily-verification .sr-dv-card{width:min(94vw,620px);max-height:92dvh;overflow:auto;border:1px solid rgba(217,183,107,.22);border-radius:22px;background:#0b0e13;box-shadow:0 30px 100px rgba(0,0,0,.55);padding:clamp(20px,4vw,34px)}#sr-daily-verification .sr-dv-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.sr-dv-kicker{font-size:10px;letter-spacing:.18em;color:#d9b76b;font-weight:900}.sr-dv-card h2{font-size:clamp(24px,5vw,34px);line-height:1.15;color:#fff;margin:7px 0}.sr-dv-muted{color:#8d98a8;font-size:13px;line-height:1.7}.sr-dv-progress{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:20px 0}.sr-dv-progress span{height:5px;border-radius:99px;background:#202631}.sr-dv-progress span.on{background:#d9b76b}.sr-dv-question{font-size:17px;line-height:1.55;color:#f1f5f9;font-weight:800;margin:18px 0}.sr-dv-options{display:grid;gap:9px}.sr-dv-option{width:100%;min-height:52px;padding:12px 14px;text-align:left;border:1px solid #27303c;border-radius:13px;background:#11161d;color:#dbe2ea;font-size:14px;font-weight:700;cursor:pointer;transition:.16s}.sr-dv-option:hover{border-color:#d9b76b;background:#171c24}.sr-dv-option.correct{border-color:#34d399;background:rgba(16,185,129,.08)}.sr-dv-option.wrong{border-color:#fb7185;background:rgba(244,63,94,.08)}.sr-dv-feedback{min-height:48px;margin-top:14px;padding:11px 13px;border-radius:12px;background:#11161d;color:#aab4c3;font-size:12px;line-height:1.6}.sr-dv-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}.sr-dv-btn{min-height:46px;padding:0 18px;border-radius:12px;border:1px solid #303846;background:#151a21;color:#dbe2ea;font-weight:800}.sr-dv-btn.primary{background:#d9b76b;border-color:#d9b76b;color:#101116}.sr-dv-result{text-align:center;padding:12px 0}.sr-dv-result .score{font-size:42px;font-weight:900;color:#e8c879}.sr-dv-lock{margin-top:16px;padding:11px 13px;border:1px solid rgba(217,183,107,.14);border-radius:12px;color:#929dad;font-size:11px;line-height:1.6}@media(max-width:640px){#sr-daily-verification{padding:0}.sr-dv-card{border-radius:0!important;min-height:100dvh;width:100%!important;max-height:100dvh!important;padding:22px 18px!important}.sr-dv-actions{position:sticky;bottom:0;padding-top:12px;background:linear-gradient(transparent,#0b0e13 25%)}}`;
  const inject=()=>{if(!document.getElementById('sr-dv-style')){const s=document.createElement('style');s.id='sr-dv-style';s.textContent=css;document.head.appendChild(s)}};
  const isMember=()=>{const s=window.state||{};return Boolean(s.userData&&((s.userData.status&&['approved','active','pending'].includes(String(s.userData.status).toLowerCase()))||s.userData.nickname||s.userData.userId))||sessionStorage.getItem('sr_secure_member_id')||localStorage.getItem('sr_username')};
  const completed=()=>{try{return localStorage.getItem(KEY)===DAY()}catch{return false}};
  const mark=()=>{try{localStorage.setItem(KEY,DAY())}catch{}};
  function pick(){return [...TASKS].sort(()=>Math.random()-.5).slice(0,3)}
  function open(){if(document.getElementById('sr-daily-verification')||completed()||!isMember()||document.getElementById('admin-main'))return;inject();const tasks=pick();let index=0,score=0,answered=false;const modal=document.createElement('div');modal.id='sr-daily-verification';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML=`<div class="sr-dv-card"><div class="sr-dv-head"><div><div class="sr-dv-kicker">DAILY MEMBER CHECK</div><h2>今日認證</h2><p class="sr-dv-muted">完成 3 個簡短任務後才能進入俱樂部。內容以 BDSM 安全、共識與會員禮儀為主。</p></div><div class="sr-dv-kicker">${DAY()}</div></div><div class="sr-dv-progress"><span></span><span></span><span></span></div><div id="sr-dv-body"></div><div class="sr-dv-lock"><i class="fa-solid fa-lock"></i> 今日完成一次即可。認證不是排名，也不影響會員等級或黃金資格。</div></div>`;document.body.appendChild(modal);const body=modal.querySelector('#sr-dv-body');const bars=[...modal.querySelectorAll('.sr-dv-progress span')];const render=()=>{answered=false;bars.forEach((b,i)=>b.classList.toggle('on',i<=index));const t=tasks[index];body.innerHTML=`<div class="sr-dv-kicker">TASK ${index+1} / 3</div><div class="sr-dv-question">${t.q}</div><div class="sr-dv-options">${t.a.map((x,i)=>`<button type="button" class="sr-dv-option" data-i="${i}">${x}</button>`).join('')}</div><div id="sr-dv-feedback" class="sr-dv-feedback">選擇最符合安全與共識原則的答案。</div><div class="sr-dv-actions"><button type="button" class="sr-dv-btn primary" id="sr-dv-next" disabled>${index===2?'完成認證':'下一題'}</button></div>`;body.querySelectorAll('.sr-dv-option').forEach(btn=>btn.onclick=()=>{if(answered)return;answered=true;const ok=Number(btn.dataset.i)===t.c;if(ok)score++;btn.classList.add(ok?'correct':'wrong');body.querySelectorAll('.sr-dv-option').forEach((b,i)=>{b.disabled=true;if(i===t.c)b.classList.add('correct')});body.querySelector('#sr-dv-feedback').textContent=(ok?'答對了。 ':'再想一下。 ')+t.n;body.querySelector('#sr-dv-next').disabled=false});body.querySelector('#sr-dv-next').onclick=()=>{if(!answered)return;if(index<2){index++;render()}else{finish()}}};const finish=()=>{if(score===3){mark();body.innerHTML=`<div class="sr-dv-result"><div class="sr-dv-kicker">VERIFIED FOR TODAY</div><div class="score">3 / 3</div><h3 class="text-xl font-black text-white mt-2">今日認證完成</h3><p class="sr-dv-muted mt-2">可以進入俱樂部。明天登入時會再次進行今日認證。</p><div class="sr-dv-actions"><button type="button" class="sr-dv-btn primary" id="sr-dv-enter">進入俱樂部</button></div></div>`;body.querySelector('#sr-dv-enter').onclick=()=>modal.remove()}else{body.innerHTML=`<div class="sr-dv-result"><div class="sr-dv-kicker">RETRY</div><div class="score">${score} / 3</div><h3 class="text-xl font-black text-white mt-2">還差一點</h3><p class="sr-dv-muted mt-2">重新完成今天的 3 題即可。這不是考試，重點是熟悉安全與共識原則。</p><div class="sr-dv-actions"><button type="button" class="sr-dv-btn primary" id="sr-dv-retry">重新開始</button></div></div>`;body.querySelector('#sr-dv-retry').onclick=()=>{index=0;score=0;tasks.splice(0,tasks.length,...pick());render()}}};render()}
  function boot(){if(document.getElementById('admin-main'))return;let tries=0;const timer=setInterval(()=>{tries++;if(isMember()){clearInterval(timer);setTimeout(open,700)}if(tries>30)clearInterval(timer)},500)};
  const observer=new MutationObserver(()=>{if(isMember()&&!completed()&&!document.getElementById('sr-daily-verification')&&!document.getElementById('admin-main'))setTimeout(open,400)});
  observer.observe(document.documentElement,{childList:true,subtree:true});
  document.addEventListener('DOMContentLoaded',boot,{once:true});boot();
})();
