// SecretRoom phase two: member safety preferences and Badge next-step guidance.
(() => {
  if(window.__SR_PHASE2_SAFETY_BADGE__)return;
  window.__SR_PHASE2_SAFETY_BADGE__=true;
  const APP_ID='secretg-production-node-tw',VERSION='20260711-phase2-safety-badge-v1';
  let raw=[],patched=false,queued=false;
  const qs=id=>document.getElementById(id),toast=(m,t='info')=>window.showToast?.(m,t),uid=()=>String(window.state?.applicationId||'');
  async function tools(){if(window.SRP?.tools)return window.SRP.tools();const a=await import('https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js'),fs=await import('https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js'),app=a.getApps()[0];if(!app)throw Error('Firebase 尚未初始化');return{db:fs.getFirestore(app),fs};}
  function pref(){const u=window.state?.userData||{};return{blocked:new Set((u.blockedUserIds||[]).map(String)),hidden:new Set((u.hiddenPostIds||[]).map(String))};}
  function patch(){if(patched||!window.state)return;const d=Object.getOwnPropertyDescriptor(window.state,'posts');if(d&&d.configurable===false)return;raw=Array.isArray(window.state.posts)?window.state.posts:[];Object.defineProperty(window.state,'posts',{configurable:true,enumerable:true,get(){const p=pref();return raw.filter(x=>!p.blocked.has(String(x.userId||''))&&!p.hidden.has(String(x.id||'')));},set(v){raw=Array.isArray(v)?v:[];}});window.SRPhase2RawPosts=()=>[...raw];patched=true;}
  async function save(field,value,on){const values=new Set((window.state?.userData?.[field]||[]).map(String));on?values.add(String(value)):values.delete(String(value));const next=[...values],{db,fs}=await tools();await fs.updateDoc(fs.doc(db,'secretg_apps',APP_ID,'applications',uid()),{[field]:next,safetyUpdatedAt:fs.serverTimestamp(),safetyUpdatedAtMs:Date.now()});window.state.userData={...(window.state.userData||{}),[field]:next};window.setGlobalFilter?.(window.state.currentFilter||'recommended');}
  function postId(card){const a=[...card.querySelectorAll('[onclick]')].map(n=>n.getAttribute('onclick')||'').join(' ');return a.match(/(?:viewSinglePost|openReportModal|toggleLike|deleteMyPost|deletePost)\(['"]([^'"]+)['"]/)?.[1]||'';}
  function hideButtons(){if(window.state?.currentTab!=='feed')return;qs('feed-posts-list')?.querySelectorAll(':scope > article,:scope > div').forEach(card=>{if(card.dataset.srSafetyAction==='1')return;const id=postId(card);if(!id)return;card.dataset.srSafetyAction='1';const b=document.createElement('button');b.className='mt-3 min-h-[40px] px-3 rounded-xl border border-slate-700 text-slate-500 text-xs font-black';b.innerHTML='<i class="fa-regular fa-eye-slash mr-1.5"></i>隱藏這篇';b.onclick=async e=>{e.stopPropagation();try{await save('hiddenPostIds',id,true);toast('這篇貼文已隱藏。','success');}catch(err){toast('無法隱藏貼文：'+err.message,'error');}};card.appendChild(b);});}
  function blockButton(){if(window.state?.currentTab!=='other-profile')return;const target=String(window.state?.viewTargetUserId||''),root=qs('dashboard-tab-content');if(!target||!root||qs('sr-block-account'))return;const blocked=pref().blocked.has(target),b=document.createElement('button');b.id='sr-block-account';b.className=`w-full min-h-[44px] rounded-xl border ${blocked?'border-emerald-500/20 text-emerald-300':'border-rose-500/20 text-rose-300'} text-xs font-black mb-4`;b.textContent=blocked?`解除封鎖 @${target}`:`封鎖 @${target}`;root.insertBefore(b,root.firstElementChild);b.onclick=async()=>{try{await save('blockedUserIds',target,!blocked);toast(blocked?`已解除封鎖 @${target}`:`已封鎖 @${target}`,'success');(qs('aside-tab-feed')||qs('mobile-tab-feed'))?.click();}catch(err){toast('封鎖設定失敗：'+err.message,'error');}};}
  function badge(){if(window.state?.currentTab!=='badge-progress')return;const root=qs('dashboard-tab-content');if(!root||qs('sr-badge-next-steps'))return;const u=window.state?.userData||{},own=raw.filter(p=>String(p.userId)===uid()),steps=[];if(!u.avatar)steps.push(['profile','補上大頭照']);if(!u.xInfo?.handle)steps.push(['x','綁定 X 帳號']);if(!own.length)steps.push(['post','發布第一篇貼文']);if(!u.isSpecElite&&u.specEliteStatus!=='pending')steps.push(['spec','申請黃金 Spec']);const c=document.createElement('section');c.id='sr-badge-next-steps';c.className='glass-panel crystal-border rounded-3xl p-5 mb-4 border border-amber-500/15';c.innerHTML=`<div class="text-xs text-amber-300 font-black">下一步</div><h3 class="text-lg text-white font-black mt-1">${steps.length?'完成這些項目可解鎖更多功能':'目前主要項目都完成了'}</h3><div class="flex flex-wrap gap-2 mt-4">${steps.map(([a,l])=>`<button data-sr-next="${a}" class="min-h-[44px] px-4 rounded-xl border border-amber-500/20 text-amber-300 text-xs font-black">${l}</button>`).join('')}</div>`;root.insertBefore(c,root.firstElementChild);c.querySelectorAll('[data-sr-next]').forEach(b=>b.onclick=()=>{const a=b.dataset.srNext;if(a==='profile')(qs('aside-profile-trigger')||qs('mobile-tab-profile'))?.click();if(a==='x')window.SRPhase2OpenXBinding?.();if(a==='post')(qs('sr-feed-compose-card')||qs('aside-btn-share')||qs('mobile-btn-share'))?.click();if(a==='spec')window.showSpecApplyModal?.();});}
  function apply(){queued=false;patch();hideButtons();blockButton();badge();document.documentElement.dataset.srPhase2SafetyBadge=VERSION;}
  function schedule(){if(queued)return;queued=true;requestAnimationFrame(apply);}
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});apply();
})();
