// SecretRoom phase two: onboarding and profile completion.
(() => {
  if (window.__SR_PHASE2_ONBOARDING__) return;
  window.__SR_PHASE2_ONBOARDING__ = true;
  const VERSION='20260711-phase2-onboarding-v1',KEY='sr_phase2_onboarding_dismissed';
  let queued=false;
  const qs=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const ownPosts=()=>{const posts=window.SRPhase2RawPosts?.()||window.state?.posts||[],id=String(window.state?.applicationId||'');return posts.filter(p=>String(p.userId)===id);};
  function progress(){const u=window.state?.userData||{};const items=[['profile','基本資料',!!u.nickname&&!!u.email&&Array.isArray(u.kinks)&&u.kinks.length>0],['avatar','大頭照',!!u.avatar],['x','X 帳號',!!u.xInfo?.handle],['post','第一篇貼文',ownPosts().length>0],['notifications','查看通知',localStorage.getItem('sr_phase2_notifications_seen')==='1'],['safety','安全設定',localStorage.getItem('sr_phase2_safety_seen')==='1']].map(([key,label,done])=>({key,label,done}));const done=items.filter(i=>i.done).length;return{items,done,percent:Math.round(done/items.length*100)};}
  function clickFirst(ids){for(const id of ids){const n=qs(id);if(n){n.click();return;}}}
  function action(name){if(name==='profile'||name==='avatar')clickFirst(['aside-profile-trigger','mobile-tab-profile']);if(name==='x')window.SRPhase2OpenXBinding?.();if(name==='post')clickFirst(['sr-feed-compose-card','aside-btn-share','mobile-btn-share']);if(name==='notifications'){localStorage.setItem('sr_phase2_notifications_seen','1');clickFirst(['aside-tab-notifications','mobile-btn-notifications']);}if(name==='safety'){localStorage.setItem('sr_phase2_safety_seen','1');window.showToast?.('其他帳號頁可使用封鎖功能；貼文下方可選擇隱藏。','info');schedule();}}
  function renderOnboarding(){if(window.state?.currentTab!=='feed'||localStorage.getItem(KEY)==='1')return;const root=qs('dashboard-tab-content');if(!root||qs('sr-phase2-onboarding'))return;const p=progress();if(p.percent===100)return;const card=document.createElement('section');card.id='sr-phase2-onboarding';card.className='glass-panel crystal-border rounded-3xl p-5 border border-cyan-500/15';card.innerHTML=`<div class="flex items-start justify-between gap-3"><div><div class="text-xs text-cyan-300 font-black">新帳號導覽</div><h3 class="text-lg text-white font-black mt-1">完成你的 SecretRoom 設定</h3><p class="text-xs text-slate-500 mt-1">已完成 ${p.done}/${p.items.length} 項。</p></div><button id="sr-onboarding-dismiss" class="w-10 h-10 rounded-full border border-slate-700 text-slate-400"><i class="fa-solid fa-xmark"></i></button></div><div class="h-2 rounded-full bg-slate-900 overflow-hidden mt-4"><span class="block h-full bg-gradient-to-r from-cyan-500 to-amber-400" style="width:${p.percent}%"></span></div><div class="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-4">${p.items.map(i=>`<button data-sr-onboard="${i.key}" class="min-h-[44px] rounded-xl border ${i.done?'border-emerald-500/20 bg-emerald-500/5 text-emerald-300':'border-slate-800 bg-slate-950/45 text-slate-300'} text-left px-3 text-xs font-black"><i class="fa-solid ${i.done?'fa-circle-check':'fa-circle'} mr-2"></i>${esc(i.label)}</button>`).join('')}</div>`;root.insertBefore(card,root.firstElementChild);qs('sr-onboarding-dismiss').onclick=()=>{localStorage.setItem(KEY,'1');card.remove();};card.querySelectorAll('[data-sr-onboard]').forEach(b=>b.onclick=()=>action(b.dataset.srOnboard));}
  function renderProfile(){if(window.state?.currentTab!=='profile')return;const root=qs('dashboard-tab-content');if(!root||qs('sr-profile-completion'))return;const p=progress(),card=document.createElement('section');card.id='sr-profile-completion';card.className='glass-panel crystal-border rounded-3xl p-5 border border-cyan-500/15 mb-4';card.innerHTML=`<div class="flex items-center justify-between gap-4"><div><div class="text-xs text-cyan-300 font-black">資料完成度</div><div class="text-2xl text-white font-black mt-1">${p.percent}%</div></div><div class="flex gap-2"><button id="sr-profile-edit-shortcut" class="min-h-[44px] px-4 rounded-xl border border-amber-500/20 text-amber-300 text-xs font-black">編輯資料</button><button id="sr-profile-x-shortcut" class="min-h-[44px] px-4 rounded-xl bg-white text-black text-xs font-black">${window.state?.userData?.xInfo?.handle?'更新 X':'綁定 X'}</button></div></div><div class="h-2 rounded-full bg-slate-900 overflow-hidden mt-4"><span class="block h-full bg-gradient-to-r from-cyan-500 to-amber-400" style="width:${p.percent}%"></span></div><div class="flex flex-wrap gap-2 mt-3">${p.items.map(i=>`<span class="px-2.5 py-1 rounded-full text-[11px] border ${i.done?'border-emerald-500/20 text-emerald-300':'border-slate-700 text-slate-500'}">${i.done?'✓':'○'} ${esc(i.label)}</span>`).join('')}</div>`;root.insertBefore(card,root.firstElementChild);qs('sr-profile-edit-shortcut').onclick=()=>window.showProfileEditModal?.();qs('sr-profile-x-shortcut').onclick=()=>window.SRPhase2OpenXBinding?.();}
  function style(){if(qs('sr-phase2-onboarding-style'))return;const s=document.createElement('style');s.id='sr-phase2-onboarding-style';s.textContent='@media(max-width:640px){#sr-profile-completion>.flex{align-items:flex-start;flex-direction:column}#sr-profile-completion>.flex>div:last-child{width:100%;display:grid;grid-template-columns:1fr 1fr}}';document.head.appendChild(s);}
  function apply(){queued=false;style();renderOnboarding();renderProfile();if(window.state?.currentTab==='notifications')localStorage.setItem('sr_phase2_notifications_seen','1');document.documentElement.dataset.srPhase2Onboarding=VERSION;}
  function schedule(){if(queued)return;queued=true;requestAnimationFrame(apply);}
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});apply();
})();
