(()=>{
if(window.__SR_UI_V5__)return;window.__SR_UI_V5__=true;
const css=`
:root{--sr-bg:#f5f6f8;--sr-surface:#fff;--sr-surface-2:#f8fafc;--sr-line:#e4e7ec;--sr-text:#182230;--sr-muted:#667085;--sr-soft:#eef1f5;--sr-accent:#765b24;--sr-accent-bg:#f7f0df;--sr-success:#067647;--sr-danger:#b42318;--sr-radius:14px;--sr-shadow:0 6px 20px rgba(16,24,40,.06)}
html,body{background:var(--sr-bg)!important;color:var(--sr-text)!important;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans TC",sans-serif!important;letter-spacing:0!important}body:before,body:after,.club-groove-bg,.ci-lounge-gradient,.ambient-spotlight{background:none!important;display:none!important}#app{background:var(--sr-bg)!important}
.font-luxury{font-family:Inter,system-ui,sans-serif!important;letter-spacing:0!important}
button,input,select,textarea{font:inherit!important}button{min-height:44px!important;border-radius:10px!important}input,select,textarea{min-height:46px!important;background:#fff!important;color:var(--sr-text)!important;border:1px solid #d7dce3!important;border-radius:10px!important;box-shadow:none!important}input:focus,select:focus,textarea:focus{outline:3px solid rgba(118,91,36,.12)!important;border-color:#a88a4e!important}
.glass-panel,.admin-section-card,.admin-summary-card,.sr-flow-shell,.sr-responsive-workspace-panel,.sr-tg-modal-card{background:#fff!important;border:1px solid var(--sr-line)!important;box-shadow:var(--sr-shadow)!important;border-radius:var(--sr-radius)!important;backdrop-filter:none!important;color:var(--sr-text)!important}
.brushed-gold{background:#182230!important;color:#fff!important;border:0!important;box-shadow:none!important}.brushed-gold:hover{background:#2b3645!important}.text-yellow-300,.text-yellow-400,.text-amber-300,.text-amber-400,.text-amber-500{color:var(--sr-accent)!important}
.sr-auth-card{width:min(100% - 32px,520px)!important;max-width:520px!important;padding:28px!important;background:#fff!important;border:1px solid var(--sr-line)!important;border-radius:16px!important;box-shadow:var(--sr-shadow)!important}.sr-auth-card h1,.sr-auth-card h2,.sr-auth-card h3{color:var(--sr-text)!important}.sr-auth-card label{color:#475467!important;font-size:13px!important}.sr-auth-note,.sr-registration-guide,.sr-spec-checklist{background:#f8fafc!important;border:1px solid var(--sr-line)!important;color:var(--sr-muted)!important;border-radius:10px!important}.sr-registration-guide{grid-template-columns:1fr!important}.sr-registration-guide span{justify-content:flex-start!important;color:#475467!important}.sr-registration-guide b{background:#eef1f5!important;color:#765b24!important}.sr-spec-checklist{font-size:12px!important}.sr-flow-shell{width:min(94vw,760px)!important;max-height:92dvh!important;overflow:auto!important;padding:0!important;background:#fff!important}.sr-flow-shell>*{background:#fff!important;color:var(--sr-text)!important}.sr-flow-step{background:#f8fafc!important;border:1px solid var(--sr-line)!important;color:#344054!important}.sr-flow-step-index{background:#f1eadb!important;color:#765b24!important}.sr-password-rules{background:#f8fafc!important;border:1px solid var(--sr-line)!important;color:#667085!important}
.sr-responsive-workspace{padding:16px!important;background:#f5f6f8!important;align-items:center!important;justify-content:center!important;overflow:auto!important}.sr-responsive-workspace-panel,.sr-dialog-telegram .sr-tg-modal-card{width:min(94vw,1040px)!important;max-width:1040px!important;max-height:92dvh!important;padding:28px!important;border-radius:16px!important;background:#fff!important;border:1px solid var(--sr-line)!important;box-shadow:0 16px 50px rgba(16,24,40,.12)!important;color:var(--sr-text)!important}.sr-dialog-edit .sr-responsive-workspace-panel,.sr-dialog-spec .sr-responsive-workspace-panel,.sr-dialog-telegram .sr-tg-modal-card{min-height:0!important}.sr-responsive-workspace-panel .bg-slate-900,.sr-responsive-workspace-panel .bg-slate-950,.sr-responsive-workspace-panel .bg-black,.sr-responsive-workspace-panel [class*="bg-gray-"],.sr-responsive-workspace-panel [class*="bg-slate-"]{background:#f8fafc!important;color:var(--sr-text)!important;border-color:var(--sr-line)!important}.sr-responsive-workspace-panel .text-white,.sr-responsive-workspace-panel .text-slate-100,.sr-responsive-workspace-panel .text-slate-200,.sr-responsive-workspace-panel .text-slate-300{color:var(--sr-text)!important}.sr-responsive-workspace-panel .text-slate-400,.sr-responsive-workspace-panel .text-slate-500,.sr-responsive-workspace-panel .text-slate-600{color:var(--sr-muted)!important}
.sr-club-nav{min-height:44px!important;padding:10px 12px!important;border-radius:10px!important;color:#667085!important;font-weight:700!important}.sr-club-nav i{color:#667085!important}.sr-club-nav:hover{background:#f2f4f7!important;color:var(--sr-text)!important}.sr-club-nav.active{background:var(--sr-accent-bg)!important;color:var(--sr-accent)!important;border-left:0!important}.sr-secondary-nav{opacity:.58!important}.sr-nav-label{padding:14px 12px 5px!important;color:#98a2b3!important;font-size:10px!important;letter-spacing:.12em!important}
.sr-club-hero,.sr-club-section,.sr-content-intro,.sr-profile-intro,.sr-tab-intro{background:#fff!important;border:1px solid var(--sr-line)!important;border-radius:16px!important;box-shadow:none!important;padding:20px!important}.sr-club-hero:after,.sr-content-intro:after,.sr-profile-intro:after,.sr-tab-intro:after{display:none!important}.sr-eyebrow{color:var(--sr-accent)!important;letter-spacing:.1em!important;font-size:11px!important}.sr-status,.sr-service,.sr-principle,.sr-milestone,.sr-preview-card{background:#fff!important;border:1px solid var(--sr-line)!important;border-radius:12px!important;box-shadow:none!important}.sr-service{min-height:88px!important}.sr-service:hover,.sr-preview-card:hover{transform:none!important;border-color:#cfd5dd!important}.sr-status b,.sr-service b,.sr-principle b,.sr-milestone b,.sr-preview-card b{color:var(--sr-text)!important}.sr-status span,.sr-service small,.sr-principle span,.sr-milestone span,.sr-preview-card span{color:#667085!important}.sr-policy-strip,.sr-member-only-note,.sr-other-profile-note{background:#f8fafc!important;border:1px solid var(--sr-line)!important;color:#667085!important;border-radius:10px!important}.sr-club-standards-card{background:#fff!important;border:1px solid var(--sr-line)!important;border-radius:14px!important}.sr-content-card{background:#fff!important;border:1px solid var(--sr-line)!important;border-radius:14px!important;box-shadow:none!important}.sr-profile-social-block,.sr-dashboard-right .sr-people-discovery-card,.sr-mobile-member-discovery{display:none!important}
[id*="register"] .glass-panel,[id*="registration"] .glass-panel,.sr-auth-card .glass-panel{background:#fff!important}.sr-flow-shell .rounded-3xl,.sr-flow-shell .rounded-2xl,.sr-flow-shell .rounded-xl{border-color:var(--sr-line)!important}.sr-flow-shell .text-amber-500,.sr-flow-shell .text-amber-400{color:var(--sr-accent)!important}.sr-flow-shell .bg-amber-500\/10,.sr-flow-shell .bg-amber-600\/10{background:var(--sr-accent-bg)!important}
.fixed.inset-0.bg-black\/95,.fixed.inset-0.bg-black\/90,.fixed.inset-0.bg-black\/80{background:rgba(16,24,40,.42)!important;backdrop-filter:blur(3px)!important}
sr-simple-task{position:fixed!important}
.sr-simple-task{position:fixed!important;inset:0!important;z-index:999999!important;display:grid!important;place-items:center!important;padding:16px!important;background:rgba(16,24,40,.42)!important}.sr-simple-task-card{width:min(560px,96vw)!important;max-height:92dvh!important;overflow:auto!important;background:#fff!important;border:1px solid var(--sr-line)!important;border-radius:16px!important;padding:24px!important;box-shadow:0 20px 60px rgba(16,24,40,.18)!important}.sr-simple-task-kicker{font-size:11px!important;font-weight:800!important;letter-spacing:.08em!important;color:var(--sr-accent)!important}.sr-simple-task h2{margin:6px 0!important;color:var(--sr-text)!important;font-size:22px!important}.sr-simple-task p{color:var(--sr-muted)!important;font-size:13px!important;line-height:1.6!important}.sr-task-question{margin-top:14px!important;padding:14px!important;border:1px solid var(--sr-line)!important;border-radius:12px!important}.sr-task-question b{color:var(--sr-text)!important;font-size:14px!important}.sr-task-option{width:100%!important;margin-top:7px!important;padding:11px 12px!important;text-align:left!important;border:1px solid var(--sr-line)!important;border-radius:10px!important;background:#fff!important;color:#344054!important;cursor:pointer!important}.sr-task-option[data-selected=true]{border-color:#a88a4e!important;background:var(--sr-accent-bg)!important;color:#5c451e!important}.sr-task-submit{margin-top:16px!important;width:100%!important;min-height:48px!important;border:0!important;border-radius:10px!important;background:#182230!important;color:#fff!important;font-weight:800!important}.sr-task-result{margin-top:12px!important;padding:10px!important;border-radius:10px!important;font-size:13px!important}.sr-task-ok{background:#ecfdf3!important;color:#067647!important}.sr-task-bad{background:#fef3f2!important;color:#b42318!important}
@media(max-width:760px){.sr-auth-card{width:calc(100vw - 24px)!important;padding:20px!important}.sr-responsive-workspace{padding:0!important}.sr-responsive-workspace-panel,.sr-dialog-telegram .sr-tg-modal-card{width:100vw!important;height:100dvh!important;max-height:none!important;border-radius:0!important;padding:18px!important}.sr-simple-task{padding:0!important}.sr-simple-task-card{width:100vw!important;height:100dvh!important;max-height:none!important;border-radius:0!important;padding:20px!important}.sr-club-hero,.sr-club-section,.sr-content-intro,.sr-profile-intro,.sr-tab-intro{padding:16px!important}.sr-status-grid,.sr-service-grid,.sr-principle-grid,.sr-milestone-grid,.sr-preview-grid,.sr-profile-intro-grid{grid-template-columns:1fr!important}}
`;
const style=document.createElement('style');style.id='sr-design-system-v5';style.textContent=css;document.head.appendChild(style);
const hideCopy=()=>{document.querySelectorAll('.sr-ui-long-copy,.admin-workspace-description').forEach(e=>e.classList.add('hidden'));document.querySelectorAll('[data-sr-ui-secondary]').forEach(e=>e.classList.add('sr-secondary-nav'))};new MutationObserver(hideCopy).observe(document.documentElement,{childList:true,subtree:true});hideCopy();
const questions=[{q:'開始 BDSM 互動前，最重要的是？',a:['確認雙方當下同意、界線與安全詞','直接開始，過程中再說','只確認自己的期待'],c:0},{q:'對方說出安全詞後，應該？',a:['立即停止並確認狀態','先完成當前動作','要求對方再次說明才停止'],c:0},{q:'對方中途改變主意時？',a:['尊重改變並停止相關互動','只要沒有說安全詞就繼續','要求完成原先約定'],c:0},{q:'活動結束後，較合適的做法是？',a:['確認彼此狀態並進行 aftercare','立即離開、不需確認','把對方的反應當成理所當然'],c:0},{q:'會員內容涉及他人時，應優先確認？',a:['對方知道並同意內容的分享範圍','只要自己覺得沒問題即可','公開後再詢問'],c:0}];
const day=()=>new Date().toISOString().slice(0,10);const key='sr_content_certified_'+day();
function openTask(){if(document.querySelector('.sr-simple-task'))return;const qs=[...questions].sort(()=>Math.random()-.5).slice(0,3);const root=document.createElement('div');root.className='sr-simple-task';root.innerHTML='<div class="sr-simple-task-card" role="dialog" aria-modal="true" aria-labelledby="sr-task-title"><div class="sr-simple-task-kicker">DAILY CHECK</div><h2 id="sr-task-title">今日認證</h2><p>完成 3 題安全與共識任務，完成後即可提交今天的會員認證。</p><div id="sr-task-list"></div><div id="sr-task-result" aria-live="polite"></div><button class="sr-task-submit" type="button">完成認證</button></div>';document.body.appendChild(root);const list=root.querySelector('#sr-task-list');qs.forEach((item,i)=>{const box=document.createElement('div');box.className='sr-task-question';box.innerHTML='<b>'+(i+1)+'. '+item.q+'</b>';item.a.forEach((answer,j)=>{const b=document.createElement('button');b.type='button';b.className='sr-task-option';b.textContent=answer;b.setAttribute('aria-pressed','false');b.onclick=()=>{box.querySelectorAll('.sr-task-option').forEach(x=>{x.dataset.selected='false';x.setAttribute('aria-pressed','false')});b.dataset.selected='true';b.setAttribute('aria-pressed','true');box.dataset.answer=j};box.appendChild(b)});list.appendChild(box)});root.querySelector('.sr-task-submit').onclick=()=>{let score=0;root.querySelectorAll('.sr-task-question').forEach((box,i)=>{if(Number(box.dataset.answer)===qs[i].c)score++});const result=root.querySelector('#sr-task-result');if(score===3){result.className='sr-task-result sr-task-ok';result.textContent='認證完成。';localStorage.setItem(key,'1');setTimeout(()=>root.remove(),350)}else{result.className='sr-task-result sr-task-bad';result.textContent='目前 '+score+'/3，請重新作答。'}}}
const isSubmit=el=>/提交會員內容|提交內容|分享動態|發布貼文/.test((el?.textContent||'').replace(/\s+/g,''));document.addEventListener('click',e=>{const el=e.target?.closest?.('button,a,[role=button]');if(!el||!isSubmit(el))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openTask()},true);
const shouldOpenDaily=()=>{if(localStorage.getItem(key)==='1')return false;const dashboard=document.querySelector('#dashboard-tab-content,.dashboard-main,#dashboard');return !!dashboard};let dailyTimer;const schedule=()=>{clearTimeout(dailyTimer);dailyTimer=setTimeout(()=>{if(shouldOpenDaily())openTask()},700)};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});schedule();
})();
